## CAREFUL WHEN SWITCHING FROM DEVELOPMENT <> PRODUCTION

name: Universal Internet of Things
logo: "/img/uiot-final.png"
markdown: kramdown
permalink: pretty
repository: uiot/uiot.github.io
description: Universal Internet of Things it's an Open Middleware for the Internet of Things. It's a Free and Open Source IoT Platform & Middleware made for any architecture. It contains a large set of tools and applications that can be used on daily tasks.

gems: [jekyll-minifier, jekyll-github-metadata, amp-jekyll, jekyll-sitemap, jekyll-seo-tag] #Comment on Development
#gems: [jekyll-tidy, jekyll-admin, jekyll-github-metadata, amp-jekyll, jekyll-sitemap, jekyll-seo-tag] #Comment on Production

jekyll-minifier:
  exclude: ['js/foundation.js', 'js/jquery.js', 'js/zepto.js']
  
ampdir: amp
twitter:
  username: universaliot
social:
  name: Universal Internet of Things
  links:
    - https://twitter.com/universaliot
    - https://www.facebook.com/universalinternetofthings
webmaster_verifications:
  google: UA-72710724-2
