name: Universal Internet of Things
markdown: kramdown
title: Universal Internet of Things
repository: uiot/uiot.github.io
permalink: pretty
collections:
  photos:
#plugins: [jekyll-admin, jekyll-minifier, jekyll-feed]
plugins: [jekyll-admin, jekyll-feed]
jekyll-minifier:
  exclude: []
