name: Universal Internet of Things
markdown: kramdown
permalink: pretty
repository: uiot/uiot.github.io
description: Universal Internet of Things it's an Open Middleware for the Internet of Things. It's a Free and Open Source IoT Platform & Middleware made for any architecture. It contains a large set of tools and applications that can be used on daily tasks.
