## CAREFUL WHEN SWITCHING FROM DEVELOPMENT <> PRODUCTION

name: Universal Internet of Things
markdown: kramdown
permalink: /404.html
permalink: /blog/:year/:month/:day/:title
repository: uiot/uiot.github.io

gems: [jekyll-minifier, jekyll-github-metadata] #Comment on Development
#gems: [jekyll-tidy, jekyll-admin, jekyll-github-metadata] #Comment on Production

jekyll-minifier:
  exclude: ['js/foundation.js', 'js/jquery.js', 'js/zepto.js']