## CAREFUL WHEN SWITCHING FROM DEVELOPMENT <> PRODUCTION

name: Universal Internet of Things
markdown: kramdown
permalink: /404.html
permalink: /blog/:year/:month/:day/:title
repository: uiot/uiot.github.io

globalurl: https://betauiot.azurewebsites.net #Comment on Development
#globalurl: http://127.0.0.1:4000 #Comment on Production

gems: [jekyll-minifier, jekyll-github-metadata] #Commenct on Development
#gems: [jekyll-tidy, jekyll-admin, jekyll-github-metadata] #Comment on Production